### ISSUE TITLE
Running as Docker image on URL sub-path

### ISSUE THREAD

**Issue by sebastian-raubach** [DidierMurilloF/FielDHub#44]
Hi there. I've been running FielDHub locally on my laptop for a while and now started looking into running a Docker image using your `Dockerfile` on a server.

I can make the application start up fine, but I run into issues with it running on a sub-path on my domain, so something like

```
https://test.domain.com/fieldhub
```

When I access the application on this path (using a reverse proxy), the app tries to load resources like JS and CSS files as well as images from `https://test.domain.com/<filename>` instead of `https://test.domain.com/fieldhub/<filename>`.

I currently cannot see a way to tell FielDHub to adjust those paths based on the folder it lives in. Is this something that is currently possible and if not, do you think you'll be able to add this in the future?

**Comment by DidierMurilloF** [comment]
Hi, could you please let me know which reverse proxy you're using (e.g., Nginx, Apache, etc.)? Knowing this will help me provide you with more specific assistance.

**Comment by sebastian-raubach** [comment]
Apache. This is basically what I've got:

```
ProxyPass        /fieldhub           http://internalserver:8963
ProxyPassReverse /fieldhub           http://internalserver:8963
```

Then the `docker-compose.yml` has this:

```
version: '3.3'
services:
    fieldhub:
        image: fieldhub:latest
        ports:
          - 8963:3838
        restart: always
        container_name: fieldhub
```
